name: Build with Gradle

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        uses: gradle/actions-internal/get-aws-secrets@v1
        if: github.repository_owner == 'gradle' # don't attempt this in forks
        with:
          role-to-assume: arn:aws:iam::992382829881:role/GHASecrets_foojay-toolchains_all
          secret-ids: |
            DEVELOCITY_ACCESS_KEY, gha/foojay-toolchains/_all/DEVELOCITY_ACCESS_KEY

      - id: determine-sys-prop-args
        uses: actions/github-script@v8
        with:
          script: |
            if (context.payload.pull_request && context.payload.pull_request.head.repo.fork) {
                core.setOutput('sys-prop-args', '-DagreePublicBuildScanTermOfService=yes -DcacheNode=us --scan')
            } else {
                core.setOutput('sys-prop-args', '-DcacheNode=us')
            }
      - uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build ${{ steps.determine-sys-prop-args.outputs.sys-prop-args }}
